version: '3.9'
services:
  mongo:
    image: 'mongo'
    container_name: mongo_container
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo_container

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend_container

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '81:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/www.samantaedu.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.samantaedu.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.samantaedu.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.samantaedu.uxlivinglab.online/privkey.pem:ro
    restart: always
    depends_on:
      - backend_container
      - frontend_container
