version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: mongo_container
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    container_name: backend_container
    env_file:
      - ./.env
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
